version: "3.8"
services:
  code:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 1337:1337
    expose:
      - 1337
    working_dir: /usr/src/app
    command: npm run start
    